### ISSUE TITLE
License/reuse

### ISSUE THREAD

**Issue by kieranjol** [atvKumar/Scene_Cut_Detection#1]
Hi!

I stumbled on your timecode functions and I'd like to use them in this project within the Irish Film Institute - https://github.com/kieranjol/IFIscripts

I need to get the duration of all files in subfolders in HH:MM:SS:FF, and it looks like your functions will do this for me. Are you OK with me using them? I do not see a license on this repo...

**Comment by atvKumar** [comment]
Sure you can, glad it helped you.
